## Klasyfikacja uzyskania kredytu

**Kacper Kaczmarski**

**Franciszek Batko**

Zbiór danych: https://www.kaggle.com/datasets/taweilo/loan-approval-classification-data

In [1]:
import kagglehub

path = kagglehub.dataset_download("taweilo/loan-approval-classification-data", output_dir="./data")

print("Path to dataset files:", path)

/home/kacper/advanced-ml/.venv/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Path to dataset files: ./data

* Typ problemu: Klasyfikacja
* Ilość rekordów: 45'000
* Liczba cech: 13 (14 cecha jako zmienna klasyfikująca)
* **Brak** brakujących danych - należy je dodać

## Podstawowe podsumowanie zbioru danych

W tej sekcji przedstawiamy podstawowe informacje o zbiorze: rozmiar, typy danych, statystyki opisowe oraz listę cech.

In [2]:
import pandas as pd

# Wczytanie danych z lokalnego pliku CSV
csv_path = "./data/loan_data.csv"
df = pd.read_csv(csv_path)

print("Rozmiar zbioru (wiersze, kolumny):", df.shape)
print("\nInformacje o kolumnach:")
df.info()

print("\nStatystyki opisowe dla kolumn numerycznych:")
display(df.describe())

print("\nStatystyki opisowe dla wszystkich kolumn:")
display(df.describe(include="all"))

print("\nTypy danych:")
display(df.dtypes.to_frame("dtype"))

Rozmiar zbioru (wiersze, kolumny): (45000, 14)

Informacje o kolumnach:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45000 entries, 0 to 44999
Data columns (total 14 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   person_age                      45000 non-null  float64
 1   person_gender                   45000 non-null  object
 2   person_education                45000 non-null  object
 3   person_income                   45000 non-null  float64
 4   person_emp_exp                  45000 non-null  int64
 5   person_home_ownership           45000 non-null  object
 6   loan_amnt                       45000 non-null  float64
 7   loan_intent                     45000 non-null  object
 8   loan_int_rate                   45000 non-null  float64
 9   loan_percent_income             45000 non-null  float64
 10  cb_person_cred_hist_length      45000 non-null  float64
 11  credit_score                    45000 non-null  int64
 12  previous_loan_defaults_on_file  45000 non-null  object
 13  loan_status                     45000 non-null  int64
dtypes: float64(6), int64(3), object(5)
memory usage: 4.8+ MB

Statystyki opisowe dla kolumn numerycznych:

,person_age,person_income,person_emp_exp,loan_amnt,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,loan_status
count,45000.000000,4.500000e+04,45000.000000,45000.000000,45000.000000,45000.000000,45000.000000,45000.000000,45000.000000
mean,27.764178,8.031905e+04,5.410333,9583.157556,11.006606,0.139725,5.867489,632.608756,0.222222
std,6.045108,8.042250e+04,6.063532,6314.886691,2.978808,0.087212,3.879702,50.435865,0.415744
min,20.000000,8.000000e+03,0.000000,500.000000,5.420000,0.000000,2.000000,390.000000,0.000000
25%,24.000000,4.720400e+04,1.000000,5000.000000,8.590000,0.070000,3.000000,601.000000,0.000000
50%,26.000000,6.704800e+04,4.000000,8000.000000,11.010000,0.120000,4.000000,640.000000,0.000000
75%,30.000000,9.578925e+04,8.000000,12237.250000,12.990000,0.190000,8.000000,670.000000,0.000000
max,144.000000,7.200766e+06,125.000000,35000.000000,20.000000,0.660000,30.000000,850.000000,1.000000

Statystyki opisowe dla wszystkich kolumn:

,person_age,person_gender,person_education,person_income,person_emp_exp,person_home_ownership,loan_amnt,loan_intent,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,previous_loan_defaults_on_file,loan_status
count,45000.000000,45000,45000,4.500000e+04,45000.000000,45000,45000.000000,45000,45000.000000,45000.000000,45000.000000,45000.000000,45000,45000.000000
unique,NaN,2,5,NaN,NaN,4,NaN,6,NaN,NaN,NaN,NaN,2,NaN
top,NaN,male,Bachelor,NaN,NaN,RENT,NaN,EDUCATION,NaN,NaN,NaN,NaN,Yes,NaN
freq,NaN,24841,13399,NaN,NaN,23443,NaN,9153,NaN,NaN,NaN,NaN,22858,NaN
mean,27.764178,NaN,NaN,8.031905e+04,5.410333,NaN,9583.157556,NaN,11.006606,0.139725,5.867489,632.608756,NaN,0.222222
std,6.045108,NaN,NaN,8.042250e+04,6.063532,NaN,6314.886691,NaN,2.978808,0.087212,3.879702,50.435865,NaN,0.415744
min,20.000000,NaN,NaN,8.000000e+03,0.000000,NaN,500.000000,NaN,5.420000,0.000000,2.000000,390.000000,NaN,0.000000
25%,24.000000,NaN,NaN,4.720400e+04,1.000000,NaN,5000.000000,NaN,8.590000,0.070000,3.000000,601.000000,NaN,0.000000
50%,26.000000,NaN,NaN,6.704800e+04,4.000000,NaN,8000.000000,NaN,11.010000,0.120000,4.000000,640.000000,NaN,0.000000
75%,30.000000,NaN,NaN,9.578925e+04,8.000000,NaN,12237.250000,NaN,12.990000,0.190000,8.000000,670.000000,NaN,0.000000
max,144.000000,NaN,NaN,7.200766e+06,125.000000,NaN,35000.000000,NaN,20.000000,0.660000,30.000000,850.000000,NaN,1.000000

Typy danych:

                                  dtype
person_age                      float64
person_gender                    object
person_education                 object
person_income                   float64
person_emp_exp                    int64
person_home_ownership            object
loan_amnt                       float64
loan_intent                      object
loan_int_rate                   float64
loan_percent_income             float64
cb_person_cred_hist_length      float64
credit_score                      int64
previous_loan_defaults_on_file   object
loan_status                       int64

### Lista cech i ich znaczenie

- `person_age` - wiek osoby
- `person_gender` - płeć
- `person_education` - poziom wykształcenia
- `person_income` - roczny dochód
- `person_emp_exp` - doświadczenie zawodowe (lata)
- `person_home_ownership` - status mieszkaniowy (np. RENT, OWN, MORTGAGE)
- `loan_amnt` - kwota pożyczki
- `loan_intent` - cel pożyczki
- `loan_int_rate` - oprocentowanie pożyczki
- `loan_percent_income` - udział kwoty pożyczki w dochodzie
- `cb_person_cred_hist_length` - długość historii kredytowej
- `credit_score` - scoring kredytowy
- `previous_loan_defaults_on_file` - informacja o wcześniejszych problemach ze spłatą
- `loan_status` - zmienna zależna (etykieta klasyfikacji: 0/1)

Zbiór danych nadaje się do klasyfikacji binarnej. Zmienną zależną jest `loan_status`, a pozostałe cechy opisują profil klienta, parametry pożyczki oraz historię kredytową.

## Imputacja danych błędnych i brakujących

 > Założenie: kolumna docelowa `loan_status` nie może mieć braków i nie imputujemy jej.

W tym punkcie realizujemy 4 podejścia:
1. Prosta imputacja A: mediana (numeryczne) + moda (kategoryczne).
2. Prosta imputacja B: średnia (numeryczne) + moda (kategoryczne).
3. Imputacja modelowa: `KNNImputer` dla cech numerycznych + moda dla kategorycznych.
4. Imputacja AutoML: predykcja brakujących wartości w każdej kolumnie z użyciem AutoGluon.

In [1]:
import pandas as pd
import numpy as np

from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer

# Wczytanie danych z brakami wygenerowanymi wcześniej
csv_missing_path = "./data/loan_data_with_missing.csv"
df_missing = pd.read_csv(csv_missing_path)

# Kolumna klasyfikacyjna - nie imputujemy jej
target_col = "loan_status"
X = df_missing.drop(columns=[target_col]).copy()
y = df_missing[target_col].copy()

num_cols = X.select_dtypes(include=["number"]).columns.tolist()
cat_cols = X.select_dtypes(exclude=["number"]).columns.tolist()

print("Rozmiar X:", X.shape)
print("Braki w X (łącznie):", int(X.isna().sum().sum()))
print("Braki w y:", int(y.isna().sum()))
print("Kolumny numeryczne:", len(num_cols), "| kategoryczne:", len(cat_cols))

def raport_brakow(df, nazwa):
    print(f"\n[{nazwa}] Braki łącznie: {int(df.isna().sum().sum())}")
    display(df.isna().mean().sort_values(ascending=False).head(10).to_frame("missing_ratio"))

Rozmiar X: (45000, 13)
Braki w X (łącznie): 58500
Braki w y: 0
Kolumny numeryczne: 8 | kategoryczne: 5

In [2]:
# --- 1) Prosta imputacja A: mediana + moda ---
ct_simple_a = ColumnTransformer(
    transformers=[
        ("num", SimpleImputer(strategy="median"), num_cols),
        ("cat", SimpleImputer(strategy="most_frequent"), cat_cols),
    ],
    remainder="drop",
    verbose_feature_names_out=False,
).set_output(transform="pandas")

X_simple_a = ct_simple_a.fit_transform(X)
raport_brakow(X_simple_a, "Prosta A")

# --- 2) Prosta imputacja B: średnia + moda ---
ct_simple_b = ColumnTransformer(
    transformers=[
        ("num", SimpleImputer(strategy="mean"), num_cols),
        ("cat", SimpleImputer(strategy="most_frequent"), cat_cols),
    ],
    remainder="drop",
    verbose_feature_names_out=False,
).set_output(transform="pandas")

X_simple_b = ct_simple_b.fit_transform(X)
raport_brakow(X_simple_b, "Prosta B")

# --- 3) Imputacja modelowa: KNNImputer + moda ---
from sklearn.impute import KNNImputer

# Numeryczne: imputacja modelowa oparta o najblizszych sasiadow
knn_imp = KNNImputer(n_neighbors=5, weights="uniform")
X_num_knn = pd.DataFrame(knn_imp.fit_transform(X[num_cols]), columns=num_cols, index=X.index)

# Kategoryczne: prosta moda
cat_imp = SimpleImputer(strategy="most_frequent")
X_cat_imp = pd.DataFrame(cat_imp.fit_transform(X[cat_cols]), columns=cat_cols, index=X.index)

X_model_knn = pd.concat([X_num_knn, X_cat_imp], axis=1)[X.columns]
raport_brakow(X_model_knn, "Modelowa (KNNImputer)")

# Gotowe zestawy do dalszego modelowania klasyfikacji:
# X_simple_a, X_simple_b, X_model_knn oraz y (bez brakow)

[Prosta A] Braki łącznie: 0

                            missing_ratio
person_age                            0.0
person_income                         0.0
person_emp_exp                        0.0
loan_amnt                             0.0
loan_int_rate                         0.0
loan_percent_income                   0.0
cb_person_cred_hist_length            0.0
credit_score                          0.0
person_gender                         0.0
person_education                      0.0

[Prosta B] Braki łącznie: 0

                            missing_ratio
person_age                            0.0
person_income                         0.0
person_emp_exp                        0.0
loan_amnt                             0.0
loan_int_rate                         0.0
loan_percent_income                   0.0
cb_person_cred_hist_length            0.0
credit_score                          0.0
person_gender                         0.0
person_education                      0.0

[Modelowa (KNNImputer)] Braki łącznie: 0

                       missing_ratio
person_age                       0.0
person_gender                    0.0
person_education                 0.0
person_income                    0.0
person_emp_exp                   0.0
person_home_ownership            0.0
loan_amnt                        0.0
loan_intent                      0.0
loan_int_rate                    0.0
loan_percent_income              0.0

In [3]:
# --- 4) Imputacja AutoML: AutoGluon dla każdej kolumny z brakami ---
# Uwaga: to podejście jest kosztowne obliczeniowo. Trenujemy osobny model dla każdej kolumny z brakami.

df_automl = X.copy()
missing_counts = df_automl.isna().sum().sort_values(ascending=False)
cols_with_missing = missing_counts[missing_counts > 0].index.tolist()

if len(cols_with_missing) == 0:
    print("Brak brakujących wartości w cechach - AutoML nie jest potrzebny.")
else:
    try:
        from autogluon.tabular import TabularPredictor

        successful_cols = []
        failed_cols = []

        for col_to_impute in cols_with_missing:
            print(f"\nImputacja AutoML dla kolumny: {col_to_impute}")

            known_mask = df_automl[col_to_impute].notna()
            train_df = df_automl.loc[known_mask].copy()
            pred_df = df_automl.loc[~known_mask].copy()

            if len(pred_df) == 0:
                print("  Brak braków do uzupełnienia - pomijam.")
                continue
            if len(train_df) < 50:
                print("  Za mało obserwacji uczących - pomijam.")
                failed_cols.append(col_to_impute)
                continue

            # Uzupełnienie cech wejściowych, aby AutoML mogło trenować
            for c in train_df.columns:
                if c == col_to_impute:
                    continue
                if pd.api.types.is_numeric_dtype(train_df[c]):
                    med = train_df[c].median()
                    train_df[c] = train_df[c].fillna(med)
                    pred_df[c] = pred_df[c].fillna(med)
                else:
                    mode_vals = train_df[c].mode(dropna=True)
                    fill_val = mode_vals.iloc[0] if len(mode_vals) > 0 else "BRAK"
                    train_df[c] = train_df[c].fillna(fill_val)
                    pred_df[c] = pred_df[c].fillna(fill_val)

            # Typ zadania dla imputowanej kolumny
            if pd.api.types.is_numeric_dtype(train_df[col_to_impute]):
                problem_type = "regression"
            else:
                problem_type = "multiclass"
                train_df[col_to_impute] = train_df[col_to_impute].astype(str)

            try:
                predictor = TabularPredictor(
                    label=col_to_impute,
                    problem_type=problem_type
                ).fit(
                    train_data=train_df,
                    time_limit=45,
                    presets="medium_quality",
                    verbosity=0
                )

                preds = predictor.predict(pred_df.drop(columns=[col_to_impute]))
                if problem_type == "multiclass":
                    preds = preds.astype(object)

                df_automl.loc[~known_mask, col_to_impute] = preds.values
                successful_cols.append(col_to_impute)
                print(f"  OK - uzupełniono {len(pred_df)} braków")

            except Exception as e:
                failed_cols.append(col_to_impute)
                print(f"  Błąd dla kolumny {col_to_impute}: {e}")

        print("\nPodsumowanie AutoML:")
        print("Udało się imputować kolumny:", successful_cols)
        print("Nie udało się imputować kolumn:", failed_cols)
        raport_brakow(df_automl, "AutoML (wszystkie kolumny)")

    except ImportError:
        print("AutoGluon nie jest zainstalowany. Zainstaluj: pip install autogluon.tabular")
        print("Po instalacji uruchom ponownie tę komórkę.")

/home/kacper/advanced-ml/.venv/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
No path specified. Models will be saved in: "AutogluonModels/ag-20260328_072830"

Imputacja AutoML dla kolumny: person_age

No path specified. Models will be saved in: "AutogluonModels/ag-20260328_072922"

  OK - uzupełniono 4500 braków

Imputacja AutoML dla kolumny: person_gender

No path specified. Models will be saved in: "AutogluonModels/ag-20260328_073007"

  OK - uzupełniono 4500 braków

Imputacja AutoML dla kolumny: person_education

No path specified. Models will be saved in: "AutogluonModels/ag-20260328_073052"

  OK - uzupełniono 4500 braków

Imputacja AutoML dla kolumny: person_income

/home/kacper/advanced-ml/.venv/lib/python3.12/site-packages/sklearn/compose/_column_transformer.py:975: FutureWarning: The parameter `force_int_remainder_cols` is deprecated and will be removed in 1.9. It has no effect. Leave it to its default value to avoid this warning.
  warnings.warn(
No path specified. Models will be saved in: "AutogluonModels/ag-20260328_073139"

  OK - uzupełniono 4500 braków

Imputacja AutoML dla kolumny: person_emp_exp

No path specified. Models will be saved in: "AutogluonModels/ag-20260328_073226"

  OK - uzupełniono 4500 braków

Imputacja AutoML dla kolumny: person_home_ownership

No path specified. Models will be saved in: "AutogluonModels/ag-20260328_073311"

  OK - uzupełniono 4500 braków

Imputacja AutoML dla kolumny: loan_amnt

/home/kacper/advanced-ml/.venv/lib/python3.12/site-packages/sklearn/compose/_column_transformer.py:975: FutureWarning: The parameter `force_int_remainder_cols` is deprecated and will be removed in 1.9. It has no effect. Leave it to its default value to avoid this warning.
  warnings.warn(
No path specified. Models will be saved in: "AutogluonModels/ag-20260328_073400"

  OK - uzupełniono 4500 braków

Imputacja AutoML dla kolumny: loan_intent

No path specified. Models will be saved in: "AutogluonModels/ag-20260328_073446"

  OK - uzupełniono 4500 braków

Imputacja AutoML dla kolumny: loan_int_rate

/home/kacper/advanced-ml/.venv/lib/python3.12/site-packages/sklearn/compose/_column_transformer.py:975: FutureWarning: The parameter `force_int_remainder_cols` is deprecated and will be removed in 1.9. It has no effect. Leave it to its default value to avoid this warning.
  warnings.warn(
No path specified. Models will be saved in: "AutogluonModels/ag-20260328_073533"

  OK - uzupełniono 4500 braków

Imputacja AutoML dla kolumny: loan_percent_income

/home/kacper/advanced-ml/.venv/lib/python3.12/site-packages/sklearn/compose/_column_transformer.py:975: FutureWarning: The parameter `force_int_remainder_cols` is deprecated and will be removed in 1.9. It has no effect. Leave it to its default value to avoid this warning.
  warnings.warn(
No path specified. Models will be saved in: "AutogluonModels/ag-20260328_073620"

  OK - uzupełniono 4500 braków

Imputacja AutoML dla kolumny: cb_person_cred_hist_length

/home/kacper/advanced-ml/.venv/lib/python3.12/site-packages/sklearn/compose/_column_transformer.py:975: FutureWarning: The parameter `force_int_remainder_cols` is deprecated and will be removed in 1.9. It has no effect. Leave it to its default value to avoid this warning.
  warnings.warn(
No path specified. Models will be saved in: "AutogluonModels/ag-20260328_073706"

  OK - uzupełniono 4500 braków

Imputacja AutoML dla kolumny: credit_score

/home/kacper/advanced-ml/.venv/lib/python3.12/site-packages/sklearn/compose/_column_transformer.py:975: FutureWarning: The parameter `force_int_remainder_cols` is deprecated and will be removed in 1.9. It has no effect. Leave it to its default value to avoid this warning.
  warnings.warn(
No path specified. Models will be saved in: "AutogluonModels/ag-20260328_073752"

  OK - uzupełniono 4500 braków

Imputacja AutoML dla kolumny: previous_loan_defaults_on_file

/home/kacper/advanced-ml/.venv/lib/python3.12/site-packages/sklearn/compose/_column_transformer.py:975: FutureWarning: The parameter `force_int_remainder_cols` is deprecated and will be removed in 1.9. It has no effect. Leave it to its default value to avoid this warning.
  warnings.warn(

  OK - uzupełniono 4500 braków

Podsumowanie AutoML:
Udało się imputować kolumny: ['person_age', 'person_gender', 'person_education', 'person_income', 'person_emp_exp', 'person_home_ownership', 'loan_amnt', 'loan_intent', 'loan_int_rate', 'loan_percent_income', 'cb_person_cred_hist_length', 'credit_score', 'previous_loan_defaults_on_file']
Nie udało się imputować kolumn: []

[AutoML (wszystkie kolumny)] Braki łącznie: 0

                       missing_ratio
person_age                       0.0
person_gender                    0.0
person_education                 0.0
person_income                    0.0
person_emp_exp                   0.0
person_home_ownership            0.0
loan_amnt                        0.0
loan_intent                      0.0
loan_int_rate                    0.0
loan_percent_income              0.0

In [ ]:
# --- Skalowanie i zapis 8 zbiorow (4 imputacje x 2 skalowania) ---
from pathlib import Path
from sklearn.preprocessing import MinMaxScaler, StandardScaler

output_dir = Path("./data")
output_dir.mkdir(parents=True, exist_ok=True)

# Wszystkie 4 metody imputacji
imputed_datasets = {
    "simple_a": X_simple_a.copy(),
    "simple_b": X_simple_b.copy(),
    "model_knn": X_model_knn.copy(),
    "automl": df_automl.copy(),
}

def scale_numeric_columns(features_df: pd.DataFrame, scaler):
    """Skalowanie tylko kolumn numerycznych, kategorie pozostaja bez zmian."""
    scaled_df = features_df.copy()
    local_num_cols = scaled_df.select_dtypes(include=["number"]).columns.tolist()
    if local_num_cols:
        scaled_df[local_num_cols] = scaler.fit_transform(scaled_df[local_num_cols])
    return scaled_df

scalers = {
    "minmax": MinMaxScaler(),
    "standard": StandardScaler(),
}

saved_files = []

for imputation_name, features_df in imputed_datasets.items():
    for scaler_name, scaler_obj in scalers.items():
        X_scaled = scale_numeric_columns(features_df, scaler_obj)

        full_df = X_scaled.copy()
        full_df[target_col] = y.values

        out_path = output_dir / f"loan_data_{imputation_name}_{scaler_name}.csv"
        full_df.to_csv(out_path, index=False)

        saved_files.append(out_path)
        print(f"Zapisano: {out_path} | kształt: {full_df.shape}")

print(f"\nLiczba zapisanych zbiorow: {len(saved_files)}")

Zapisano: data/loan_data_simple_a_minmax.csv | kształt: (45000, 14)
Zapisano: data/loan_data_simple_a_standard.csv | kształt: (45000, 14)
Zapisano: data/loan_data_simple_b_minmax.csv | kształt: (45000, 14)
Zapisano: data/loan_data_simple_b_standard.csv | kształt: (45000, 14)
Zapisano: data/loan_data_model_knn_minmax.csv | kształt: (45000, 14)
Zapisano: data/loan_data_model_knn_standard.csv | kształt: (45000, 14)
Zapisano: data/loan_data_automl_minmax.csv | kształt: (45000, 14)
Zapisano: data/loan_data_automl_standard.csv | kształt: (45000, 14)

Liczba zapisanych zbiorow: 8